# Generated by Django 5.0.6 on 2024-05-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
